// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using qwtfarena.Persistence.Contexts;

namespace qwtfarena.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190920010929_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("qwtfarena.Domain.Models.DiscordVoiceChannel", b =>
                {
                    b.Property<string>("DiscordVoiceChannelID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("DiscordVoiceChannelID");

                    b.ToTable("DiscordVoiceChannels");
                });

            modelBuilder.Entity("qwtfarena.Domain.Models.DiscordVoiceUser", b =>
                {
                    b.Property<string>("DiscordVoiceUserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiscordVoiceChannelID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("DiscordVoiceUserID");

                    b.HasIndex("DiscordVoiceChannelID");

                    b.ToTable("DiscordVoiceUsers");
                });

            modelBuilder.Entity("qwtfarena.Domain.Models.DiscordVoiceUser", b =>
                {
                    b.HasOne("qwtfarena.Domain.Models.DiscordVoiceChannel", "DiscordVoiceChannel")
                        .WithMany("Users")
                        .HasForeignKey("DiscordVoiceChannelID");
                });
#pragma warning restore 612, 618
        }
    }
}
